version: '3'

services:
    erpapp-php:
        build:
            context: ../
            dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www/erp
        volumes:
            - '../:/var/www/erp'
        networks:
            - erp
        environment:
            - PHP_IDE_CONFIG=serverName=erp

    nginx:
        image: nginx:1.21.6-alpine
        restart: always
        ports:
            - '8090:80'
        volumes:
            - '../:/var/www/erp'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - erp
        depends_on:
            - erpapp-php

    mysql:
        container_name: mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: erp
            MYSQL_USER: erp
            MYSQL_PASSWORD: erp
        ports:
            - '3306:3306'
        networks:
            - erp

networks:
    erp:
